import streamlit as st
import os
from dotenv import load_dotenv
from groq import Groq
from typing import Dict, List
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io
from time import time
from streamlit_autorefresh import st_autorefresh

# --- SET PAGE CONFIG AND HIDE DEPLOY BUTTON ---
st.set_page_config(
    page_title="Debate Partner Bot",
    page_icon="🎤",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={},
)

st.markdown("""
<style>
.stDeployButton {display: none !important;}
header [data-testid="stToolbar"] {display: none !important;}
.user-msg {
    background-color:#DCF8C6; padding:10px; border-radius:12px; margin-bottom:10px; font-size:16px;
}
.assistant-msg {
    background-color:#FFF9C4; padding:10px; border-radius:12px; margin-bottom:10px; font-size:16px;
}
.debate-turn-count {
    font-weight: bold;
    font-size: 16px;
    margin-bottom: 10px;
}
.quote {
    font-style: italic; color: #555; margin-top: 15px; border-left: 4px solid #6a11cb;
    padding-left: 12px; margin-bottom: 15px; font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
    background: #f9f9f9; border-radius: 8px;
}
</style>
""", unsafe_allow_html=True)

load_dotenv()
GROQ_API_KEY = os.getenv("GROQ_API_KEY")


@st.cache_resource
def get_groq_client_cached(api_key=None):
    if api_key is None:
        api_key = GROQ_API_KEY
    if not api_key:
        st.warning("⚠ Groq API key missing. Please set it in .env or Streamlit secrets.")
        return None
    return Groq(api_key=api_key)


def init_state():
    defaults = {
        "messages": [],
        "user_name": "",
        "user_email": "",
        "debate_active": False,
        "debate_topic": "",
        "debate_style": "Formal",
        "debate_level": "Medium",
        "conclusion": None,
        "is_processing": False,
        "turn_count": 0,
        "debate_tip": "Keep your arguments clear and respectful.",
    }
    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v


def generate_pdf(messages: List[Dict[str, str]]) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    y = height - 40
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Debate Transcript")
    y -= 40
    c.setFont("Helvetica", 12)
    for msg in messages:
        text = f"{msg['role'].capitalize()}: {msg['content']}"
        for line in text.split("\n"):
            wrapped_lines = [line[i:i+90] for i in range(0, len(line), 90)]
            for wrapped in wrapped_lines:
                if y < 40:
                    c.showPage()
                    c.setFont("Helvetica", 12)
                    y = height - 40
                c.drawString(50, y, wrapped)
                y -= 20
    c.drawString(50, 30, "Generated by Debate Partner Bot 🎤")
    c.save()
    buffer.seek(0)
    return buffer


def update_debate_tip(user_msg: str):
    tips_map = {
        "ai": "Remember AI can augment humans, not just replace.",
        "jobs": "Automation impacts job markets; consider carefully.",
        "privacy": "Privacy issues are vital in tech debates.",
        "ethics": "Ethical AI use is essential in debates.",
        "education": "Educate to use AI responsibly.",
        "future": "Think long-term impact and society's good.",
    }
    text_lower = user_msg.lower()
    for k, tip in tips_map.items():
        if k in text_lower:
            return tip
    return "Keep arguments clear, concise, and respectful."


@st.cache_data(show_spinner=False)
def generate_opposite_response_cached(api_key, user_message, style, level, debate_topic):
    client = get_groq_client_cached(api_key)
    if not client:
        return "⚠ Unable to generate response. API key missing."

    level_prompt = {
        "Easy": "Use simple, clear, brief responses.",
        "Medium": "Use balanced, clear, respectful arguments.",
        "Hard": "Use detailed, logical, complex arguments."
    }[level]

    system_prompt = f"""
You are Debate Partner Bot 🎤 taking the OPPOSITE stance on: {debate_topic}.
Debate style: {style}.
Challenge level: {level}.
{level_prompt}
Be respectful, logical and engaging.

⚠ Important: If user's input is incomplete or abrupt, complete it logically, then counter it. Always provide a concise, complete, and meaningful short counter-argument of 3–5 sentences, ending with a strong statement.
""".strip()

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message},
    ]

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=messages,
        temperature=0.6,
        max_tokens=256,
        stream=False,
    )
    return response.choices[0].message.content.strip()


@st.cache_data(show_spinner=False)
def generate_conclusion_cached(api_key, messages):
    client = get_groq_client_cached(api_key)
    if not client:
        return "⚠ Unable to generate conclusion. API key missing."

    debate_text = "\n".join([f"{m['role'].capitalize()}: {m['content']}" for m in messages])
    system_prompt = """
You are a Debate Summarizer Bot 📝.
Summarize the debate neutrally and concisely (3–5 lines).
""".strip()

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": debate_text},
        ],
        temperature=0.7,
        max_tokens=150,
    )
    return response.choices[0].message.content.strip()


# 200+ quotes related to debate / AI / critical thinking / communication
QUOTES = [
    "The art of debate is the art of thinking made visible.",
    "Strong arguments rely on calm minds.",
    "Every discussion is an opportunity to refine your reasoning.",
    "Great debaters listen twice as much as they speak.",
    "AI challenges humans to think more clearly, not less.",
    "Clarity in words reflects clarity in thought.",
    "Logic is the bridge between knowledge and wisdom.",
    "Those who learn to argue well, learn to think deeply.",
    "Respect in disagreement defines maturity.",
    "The purpose of arguing is not victory, but understanding.",
    "Progress begins with questioning assumptions.",
    "Debate sharpens intellect like whetstone sharpens steel.",
    "Ideas are tested, not people.",
    "Confidence in dialogue is born from preparation.",
    "To argue well, one must listen better.",
    "Rational debate inspires innovation.",
    "Criticism refines thought more than praise ever can.",
    "Think, question, evolve.",
    "The wisest debaters learn from every counterpoint.",
    "A respectful debate is a civilized exchange of truth.",
    "A strong argument stands on evidence, not emotion.",
    "There is no progress without constructive disagreement.",
    "A debate without respect is noise, not discussion.",
    "Learning is the journey; questioning is the path.",
    "Let the best ideas win, not the loudest voices.",
    "Curiosity is the engine of smart discussion.",
    "Thoughtful challenge leads to lasting progress.",
    "Every point of view is a window to new wisdom.",
    "Seek clarity, not certainty.",
    "Disagreement is not disrespect.",
    "Listening is half of winning any debate.",
    "Questions reveal more than answers.",
    "A wise mind welcomes every valid challenge.",
    "An idea untested is an opportunity wasted.",
    "AI can amplify human debate, not replace human judgment.",
    "True leaders engage in humble conversation.",
    "Every argument is a step closer to understanding.",
    "Seek truth, not victory.",
    "Growth starts where comfort ends.",
    "Polite words are powerful tools.",
    "The best debater is a consistent learner.",
    "Speak, not to win, but to enlighten.",
    "Debate is the laboratory of ideas.",
    "Clever arguments are built, not improvised.",
    "Change emerges from tested conversations.",
    "Let logic be your compass, not your armor.",
    "To persuade, first understand.",
    "An open mind is a powerful ally.",
    "Challenge ideas, not identities.",
    "Informed debate plants seeds of wisdom.",
    "Accepting uncertainty is the start of wisdom.",
    "Debate reveals the depth of understanding.",
    "Complex problems require collaborative debate.",
    "Big ideas demand bigger questions.",
    "Be curious, not combative.",
    "The best answers come from persistent questions.",
    "Respect the question and value the answer.",
    "A single honest debate can change your worldview.",
    "The courage to change your mind shows true strength.",
    "AI-powered debate is a new frontier of learning.",
    "Let evidence be your guide.",
    "Disagreement drives progress.",
    "Every view is a link in the chain of discovery.",
    "To discuss is to discover.",
    "Controversy can be the catalyst of thought.",
    "Ideas mature in conversation.",
    "Fearless debate fosters creative solutions.",
    "Curiosity turns debate into discovery.",
    "Learn to challenge yourself before others.",
    "Dialogue overcomes division.",
    "No opinion is immune to improvement.",
    "The most difficult argument is often the most important.",
    "Questions open doors; answers may close them.",
    "Challenge with kindness, defend with facts.",
    "Humility makes great thinkers.",
    "Sharp minds ask sharper questions.",
    "Wisdom listens even when it disagrees.",
    "Debate is not about defeating others, but defeating ignorance.",
    "A single reason can outweigh a thousand emotions.",
    "Question everything, especially your own beliefs.",
    "Dissent, well guided, is a force for progress.",
    "True strength is adjusting your beliefs to new evidence.",
    "Ideas, like steel, are strengthened by collision.",
    "The best collaborators argue with purpose, not with malice.",
    "AI offers perspective; humans offer values.",
    "Win the argument, but never lose the person.",
    "Discussion is not about winning but about learning.",
    "Speak with passion; respond with patience.",
    "The only foolish question is the one unasked.",
    "Constructive criticism fuels progress.",
    "The best debaters can argue both sides clearly.",
    "Knowledge grows when we dare to question.",
    "A well-posed question is half the answer.",
    "The future belongs to those who debate with integrity.",
    "Debate builds bridges between diverse ideas.",
    "Every argument is a chance to clarify your values.",
    "Critical thinking is the art of weighing every word.",
    "A debate is a dance of logic and empathy.",
    "Answers are easy; good questions are rare.",
    "Don’t fear the counterargument; embrace it.",
    "The mind grows strong where ideas collide.",
    "Respect is debate's anchor.",
    "To master a lesson, debate it.",
    "Seek truth over victory and dialogue over dispute.",
    "A great mind is forged in the fire of discussion.",
    "You don't have to agree to understand.",
    "Growth thrives on well-meaning criticism.",
    "Conflict handled wisely leads to progress.",
    "Truth often reveals itself in the contest of ideas.",
    "Listening sharpens your response.",
    "Argue, not for conquest, but for clarity.",
    "Logic builds bridges, not walls.",
    "Communication breeds understanding.",
    "True understanding requires questioning both sides.",
    "Every new conversation is a blank page.",
    "The voice of reason rises above the noise.",
    "Dialogue wins hearts before minds.",
    "Agree to disagree—and keep learning.",
    "The most persuasive debater is the most respectful.",
    "Never ignore a good argument, even if it’s not yours.",
    "Curiosity and humility open endless debates.",
    "Honesty is the foundation of every strong argument.",
    "Compassion brings more allies than cleverness.",
    "The best debates end in respect, not resentment.",
    "Never argue for the sake of ego; argue for insight.",
    "The world changes when people truly listen.",
    "Challenging ideas is the first step to innovation.",
    "Let disagreement inspire curiosity, not anger.",
    "To win a mind, first respect a person.",
    "Critical thinking is lifelong training for the mind.",
    "Ideas flourish in the light of debate.",
    "An answer unchallenged may hide an error.",
    "Integrity in discussion commands trust.",
    "Logic must walk hand in hand with empathy.",
    "Every reason has a root; find it.",
    "The wise never stop questioning.",
    "Let questions lead you forward.",
    "Wisdom is choosing which battles to fight.",
    "All discovery starts with doubt.",
    "Challenge old ideas to make room for better ones.",
    "Change walks in on the heels of honest debate.",
    "Find the truth that bridges divides.",
    "Argue less about people, more about principles.",
    "Innovation rises from the ashes of old assumptions.",
    "Learn something from every opponent.",
    "A fair debate is a shared victory.",
    "No mind is fully closed if the heart is open.",
    "You don't lose by being corrected; you win by learning.",
    "Share your reasons openly; listen with intention.",
    "Debate is collaboration in disguise.",
    "True wisdom questions itself often.",
    "Knowledge is the light; debate is the prism.",
    "Every answer deserves to be tested.",
    "Empathy makes arguments persuasive.",
    "Fairness is the soul of productive discourse.",
    "Progress is the product of respectful disagreement.",
    "Reason draws boundaries; empathy builds bridges.",
    "Discuss to learn; concede to grow.",
    "AI can challenge your logic, but only you can accept the truth.",
    "Graciousness outlasts cleverness.",
    "Critical thinking begins with one word: why.",
    "Debate is a shared pursuit of truth.",
    "Open minds create open futures.",
    "Skillful questioning marks a wise debater.",
    "The strongest arguments survive the toughest scrutiny.",
    "Growth is found in intellectual discomfort.",
    "Conversation is a quiet engine of progress.",
    "Every debate is a blueprint for growth.",
    "Ideas gain strength from opposition.",
    "True respect is reflected in careful listening.",
    "Trust is the foundation of deep dialogue.",
    "Debate is a rehearsal for social progress.",
    "Disagreement handled with grace plants understanding.",
    "Humble learners become powerful debaters.",
    "Every belief deserves reexamination.",
    "The most important word in debate is 'why'.",
    "Careful listening is the first step toward valid argument.",
    "New perspectives arise from open conversation.",
    "Mutual respect makes hard topics easier.",
    "Change your mind gladly when evidence is strong.",
    "False certainty is the enemy of honest debate.",
    "Courage invites the difficult conversation.",
    "Think deeply; respond gently.",
    "Beliefs should move when truth moves.",
    "Conclusions built in debate are stronger than those built alone.",
    "Perspective is the invisible partner of every argument.",
    "A weaker argument can still reveal a stronger mind.",
    "Every exchange is a chance to be surprised.",
    "Questions expose the heart of the matter.",
    "Honor your opponent’s view as you hope they honor yours.",
    "Wisdom multiplies with every justified doubt.",
    "Lighting another’s idea never dims your own.",
    "Let conviction be firm but kindness stronger.",
    "Understanding begins where certainty ends.",
    "Gracious humility is debate’s greatest power.",
    "New knowledge is the child of curiosity and discussion.",
    "The right question is more powerful than the right answer.",
    "Aim not to defeat, but to illuminate.",
    "Patience creates space for deeper insight.",
    "Ideas refined by challenge tend to endure.",
    "The most valuable debates are often the hardest to start.",
    "Reason does not reside in loud voices.",
    "Defend your ideas, not your ego.",
    "Every good debate is a hidden lesson.",
    "Opponents in debate can become partners in discovery.",
    "Agreement is optional; respect is required.",
    "Find the merit in every disagreement.",
    "Silence can be as powerful as a well-posed question.",
    "Debate transforms doubts into direction.",
    "Speak your mind—and expand it when needed.",
    "Every error in argument is a gift for learning.",
    "Be patient with confusion; it precedes clarity.",
    "Embrace uncertainty; it is the root of inquiry.",
    "The best solutions emerge between differing views.",
    "Stay curious even when you strongly disagree.",
    "A wise debater seeks to inform, not to impress.",
    "Let every debate refine how you think, not just what you think.",
    "Debate without hostility creates room for progress.",
    "The clearest insight often comes after the toughest question.",
    "Let skepticism be balanced by respect.",
    "The journey of inquiry is never truly complete.",
    "True confidence includes the ability to say, 'I was wrong'.",
    "One good question can shift an entire perspective.",
    "Debate is not the end, but the beginning of wisdom.",
    "A question unasked is an opportunity missed.",
    "Reluctance to challenge is reluctance to grow.",
    "Wisdom is found more in the pursuit than in the arrival.",
    "Understanding is the ultimate outcome of every meaningful debate.",
]


def main():
    init_state()

    # Auto-refresh the app every 5 seconds (5000 milliseconds)
    st_autorefresh(interval=5000, key="auto_refresh_quotes")

    st.markdown("""
    <div style='text-align:center; padding:25px; background: linear-gradient(90deg, #6a11cb 0%, #2575fc 100%);
    border-radius: 15px; color: white; font-family: Arial, sans-serif;'>
        <h1 style='margin-bottom: 0;'>🎤 Welcome to Debate Partner Bot</h1>
        <p style='font-weight: bold; font-size: 18px;'>Challenge your ideas. Sharpen your thinking. Debate with AI.</p>
    </div><br>
    """, unsafe_allow_html=True)

    with st.sidebar:
        st.header("👤 User Info")
        if st.session_state.user_name:
            st.markdown(f"Name: {st.session_state.user_name}")
        if st.session_state.user_email:
            st.markdown(f"Email: {st.session_state.user_email}")
        if st.session_state.debate_topic:
            st.markdown(f"Topic: {st.session_state.debate_topic}")
        if st.session_state.debate_style:
            st.markdown(f"Style: {st.session_state.debate_style}")
        if st.session_state.debate_level:
            st.markdown(f"Challenge Level: {st.session_state.debate_level}")
        st.markdown("---")
        st.header("⚙ Debate Controls")
        if st.button("📄 Download Debate as PDF"):
            pdf_buffer = generate_pdf(st.session_state.messages)
            st.download_button("⬇ Save PDF", data=pdf_buffer, file_name="debate.pdf", mime="application/pdf")
        if st.button("🛑 End Debate with Conclusion"):
            if st.session_state.messages:
                with st.spinner("Summarizing debate..."):
                    conclusion = generate_conclusion_cached(GROQ_API_KEY, st.session_state.messages)
                    st.session_state.conclusion = conclusion
                    st.session_state.messages.append({
                        "role": "assistant",
                        "content": f"📝 Conclusion:\n{conclusion}"
                    })
            st.session_state.debate_active = False
        if st.button("🧹 Clear History"):
            st.session_state.messages = []
            st.session_state.conclusion = None
            st.session_state.debate_active = False
            st.success("Chat history cleared ✅")
        with st.sidebar.expander("💡 Debate Tips", expanded=True):
            st.markdown(f"<div class='debate-tip'>{st.session_state.get('debate_tip', '')}</div>", unsafe_allow_html=True)
        st.markdown("---")
        st.header("🔥 Debate Challenge Level")
        level = st.selectbox(
            "Select challenge difficulty:",
            ["Easy", "Medium", "Hard"],
            index=["Easy", "Medium", "Hard"].index(st.session_state.debate_level)
        )
        st.session_state.debate_level = level

    col1, col2 = st.columns([3, 1])

    with col1:
        if not st.session_state.debate_active and not st.session_state.conclusion:
            with st.form("onboarding_form"):
                st.subheader("👤 Enter details to start debate:")
                name = st.text_input("Your Name", value=st.session_state.user_name)
                email = st.text_input("Email", value=st.session_state.user_email)
                topic = st.text_input(
                    "Debate Topic",
                    placeholder="e.g., AI is good for humanity",
                    value=st.session_state.debate_topic,
                )
                style = st.selectbox(
                    "Debate Style",
                    ["Formal", "Casual", "Academic", "Friendly"],
                    index=["Formal", "Casual", "Academic", "Friendly"].index(st.session_state.debate_style),
                )
                submitted = st.form_submit_button("Start Debate 🎯")
                if submitted:
                    if not name or not email or not topic:
                        st.error("⚠ Please fill in all details before starting.")
                    else:
                        st.session_state.user_name = name
                        st.session_state.user_email = email
                        st.session_state.debate_topic = topic
                        st.session_state.debate_style = style
                        st.session_state.debate_active = True
                        st.session_state.messages = []
                        st.session_state.conclusion = None
                        st.session_state.turn_count = 0
                        st.session_state.debate_tip = "Keep your arguments clear and respectful."
                        st.session_state.messages.append({
                            "role": "assistant",
                            "content": f"🎯 Debate on: \"{topic}\" started. Please share your argument."
                        })
                        st.success(f"Welcome {name}! Debate started.")

        if st.session_state.debate_active:
            st.session_state.messages = st.session_state.messages[-25:]
            for msg in st.session_state.messages:
                css_class = "user-msg" if msg["role"] == "user" else "assistant-msg"
                with st.chat_message(msg["role"]):
                    st.markdown(f"<div class='{css_class}'>{msg['content']}</div>", unsafe_allow_html=True)
            prompt = st.chat_input("Enter your argument...", disabled=st.session_state.is_processing)
            if prompt and not st.session_state.is_processing:
                st.session_state.is_processing = True
                st.session_state.messages.append({"role": "user", "content": prompt})
                st.session_state.turn_count += 1
                with st.chat_message("user"):
                    st.markdown(f"<div class='user-msg'>{prompt}</div>", unsafe_allow_html=True)
                with st.chat_message("assistant"):
                    placeholder = st.empty()
                    placeholder.markdown("<em>🤖 Thinking...</em>")
                    response = generate_opposite_response_cached(
                        GROQ_API_KEY,
                        prompt,
                        st.session_state.debate_style,
                        st.session_state.debate_level,
                        st.session_state.debate_topic,
                    )
                    placeholder.markdown(f"<div class='assistant-msg'>{response}</div>", unsafe_allow_html=True)
                st.session_state.debate_tip = update_debate_tip(prompt)
                st.session_state.messages.append({"role": "assistant", "content": response})
                st.session_state.is_processing = False

        if st.session_state.conclusion and not st.session_state.debate_active:
            st.subheader("📌 Debate Conclusion")
            st.info(st.session_state.conclusion)

    # --- Quote section (auto-changes every 5 seconds due to st_autorefresh) ---
    with col2:
        st.markdown(
            f"<div class='debate-turn-count'>Debate turns: {st.session_state.turn_count}</div>",
            unsafe_allow_html=True
        )
        st.markdown("### 🌟 Inspirational Quote")

        refresh_interval = 5  # seconds
        current_time = int(time())
        quote_index = (current_time // refresh_interval) % len(QUOTES)
        current_quote = QUOTES[quote_index]

        st.markdown(f"<div class='quote'>{current_quote}</div>", unsafe_allow_html=True)


if __name__ == "__main__":
    main()
